module:
  classifier: "ResNet50"
  optimizer: "Adam"
  backbone: ''
  pretrained: ''
  loss: "WMCL"
  scheduler: "Exp_980d"

seed: 3407
dataset: 'Avg_Aug_7'
test_set: 'Avg_gd_7'
store: False
num_workers: 0
in_dimensions: [0, 7]
test_size: 0.25
img_size: 512
bs: 3
max_epoch: 120
lr: 0.000008
backbone_layers: [3, 4, 23, 3]
attention_layers: [4, 2]