module:
  classifier: "ResNet50"
  optimizer: "Adam"
  backbone: ''
  pretrained: ''
  loss: "CrossEntropy"
  scheduler: "Exp_980d"

seed: -1
dataset: 'Avg_Aug'
test_set: 'Avg_gd'
store: False
num_workers: 0
in_dimensions: [0, 5]
test_size: 0.25
img_size: 512
bs: 4
max_epoch: 80
lr: 0.000008
backbone_layers: [3, 4, 23, 3]
attention_layers: [4, 2]